#define ROOTFS_DEVNO (( << 4) | )
#define ROOTFS_TYPE ""
#define INIT_PATH ""
#define INIT_CONSOLE_DEVNO 
#define PROC_MAXFILES 32
#define VFS_MAXFILES 32
#define BOARD_TYPE mcxa153
#define BOARD_MCXA153
#define USART_DRIVER
#define USART_DRIVER_MCXA
#define HD44XXX_DRIVER
#define HD44XXX_DRIVER_HD44780
#define HD44XXX_DRIVER_ST7920
